name: tu_estilo_tu_camino
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # GetX for state management and navigation
  get: ^4.6.5

  # GetStorage for local storage (used to store session tokens, etc.)
  get_storage: ^2.1.1

  # email_validator for validating email format in login
  email_validator: ^2.0.1

  # http package for API requests
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # Include all images in the assets/images directory
